application: facebook-web-clients
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /test
  static_dir: test
- url: /.*
  script: main.app